env: "local"
http_server:
  address: "localhost:8082"
jwt:
  secret: "dev-only-secret-change-me"
  expires_in: "24h"
postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "students_api"
  sslmode: "disable"
